let data=[
{
    img:"https://logodix.com/img/a.png",
    name:"Angular"
},
{
    img:"https://logodix.com/img/b.png",
    name:"Bootstrap"
},
{
    img:"https://logodix.com/img/c.png",
    name:"CSS"
},
{
    img:"https://logodix.com/img/d.png",
    name:"Django"
},
{
    img:"https://logodix.com/img/e.png",
    name:"ES6"
},
{
    img:"https://logodix.com/img/f.png",
    name:"Figma"
},
{
    img:"https://logodix.com/img/g.png",
    name:"Github"
},
{
    img:"https://logodix.com/img/h.png",
    name:"HTML"
},
{
    img:"https://logodix.com/img/i.png",
    name:"Ionic"
},
{
    img:"https://logodix.com/img/j.png",
    name:"JavaScript"
},
{
    img:"https://logodix.com/img/k.png",
    name:"Kubernetes"
},
{
    img:"https://logodix.com/img/l.png",
    name:"Leetcode"
},
{
    img:"https://logodix.com/img/m.png",
    name:"MongoDB"
},
{
    img:"https://logodix.com/img/n.png",
    name:"NodeJs"
},
{
    img:"https://logodix.com/img/o.png",
    name:"Oracle"
},
{
    img:"https://logodix.com/img/p.png",
    name:"Python"
},
{
    img:"https://logodix.com/img/q.png",
    name:"Quokka"
},
{
    img:"https://logodix.com/img/r.png",
    name:"Rust"
},
{
    img:"https://logodix.com/img/s.png",
    name:"SQL"
},
{
    img:"https://logodix.com/img/t.png",
    name:"TypeScript"
},
{
    img:"https://logodix.com/img/u.png",
    name:"Ubuntu"
},
{
    img:"https://logodix.com/img/v.png",
    name:"Visual Studio"
},
{
    img:"https://logodix.com/img/w.png",
    name:"Webpack"
},
{
    img:"https://logodix.com/img/x.png",
    name:"XML"
},
{
    img:"https://logodix.com/img/y.png",
    name:"Yarn"
},
{
    img:"https://logodix.com/img/z.png",
    name:"Z-Shell"
},
]
export default data;